### ISSUE TITLE
不显示字数统计和阅读时长

### ISSUE THREAD

**Issue by 21sta** [theme-next/hexo-symbols-count-time#10]
怎么回事？

**Comment by ivan-nginx** [comment]
請用英文寫。

**Comment by xiaotan828** [comment]
I so sorry, I read the previous issues and I got the answer. If you are using Next theme, you need to do two things.
One is to make sure you have configure this plugin correct. 
The second is very important and I think lots of people will miss this step and meet problems. You have to add this  in your **hexo** _config.yml file. 
```
symbols_count_time:
  symbols: true
  time: true
  total_symbols: true
  total_time: true
```
