### ISSUE TITLE
What does the total mean in config?

### ISSUE THREAD

**Issue by LEAFERx** [theme-next/hexo-symbols-count-time#2]
like total_symbols and total_time in hexo config
and item_text_total in theme config

**Comment by ivan-nginx** [comment]
```yml
symbols_count_time:
  symbols: true — symbols of each post, showed at post meta.
  time: true — time to read of each post, showed at post meta.
  total_symbols: true — total symbols of all posts in whole site, showed at footer.
  total_time: true — total time to read of all posts in whole site, showed at footer.
```

```yml
symbols_count_time:
  separated_meta: true — separated meta mean what `symbols` & `time` at each post will be removed on new div block, new line. Useful if your posts meta too long.
  item_text_post: true — item text showed, or only count of `symbols` & `time` at each post in meta. It's like with date `post_meta.item_text`, if need show shorter line, useful for long language words.
  item_text_total: false — same as above, but only for `total_symbols` & `total_time`, which will display in footer.
  awl: 5 — Average Word Length. See main plugin readme at the bottom.
  wpm: 200 — Words Per Minute. See main plugin readme. See main plugin readme at the bottom.
```

Just try to on/off this settings and see on changes, all settings have visible status and u can easy to distinguish difference.
