### ISSUE TITLE
I have modified the configuration file, but the page doesn't show（我已经修改了配置文件，但页面没有显示）

### ISSUE THREAD

**Issue by Cynthia0329** [theme-next/hexo-symbols-count-time#22]
- first
```shell
$ npm install hexo-symbols-count-time -save
```

- 博客配置文件   _config.yml

```shell
symbols_count_time:
symbols: true
time: true
total_symbols: true
total_time: true
```
- 主题配置文件   theme/next/_config.yml
```shell
symbols_count_time:
  separated_meta: true
  item_text_post: true
  item_text_total: false
  awl: 4
  wpm: 275
```

- and bash
```shell
$ hexo clean
$ hexo server
```

but 
![](https://raw.githubusercontent.com/Cynthia0329/images/master/img/20190423141446.png)

**Comment by stevenjoezhang** [comment]
博客配置文件` _config.yml`有缩进嘛
```
symbols_count_time:
  symbols: true
  time: true
  total_symbols: true
  total_time: true
```
