### ISSUE TITLE
No use by changing the parameter `awl` and `wpm`.

### ISSUE THREAD

**Issue by chuxubank** [theme-next/hexo-symbols-count-time#3]
Here is my config.
In next:
```
symbols_count_time:
  separated_meta: true
  item_text_post: true
  item_text_total: false
  awl: 25
  wpm: 275
```
In hexo:
```
symbols_count_time:
  symbols: true
  time: true
  total_symbols: false
  total_time: true
```
But the word count and reading time are completely the same when I use the default setting, and I don't think they are correct.
I have used `hexo clean` but it still not work.
I wonder if there are any other settings I need to change to make it work.
Btw, is the basis of reading time hour?

**Comment by ivan-nginx** [comment]
With standart settings:
```yml
symbols_count_time:
  separated_meta: true
  item_text_post: true
  item_text_total: false
  awl: 5
  wpm: 200
```
![image](https://user-images.githubusercontent.com/16944225/34970267-82f7700c-fa84-11e7-9e69-7374c22cdea0.png)

With your settings:
```yml
symbols_count_time:
  separated_meta: true
  item_text_post: true
  item_text_total: false
  awl: 25
  wpm: 275
```
![image](https://user-images.githubusercontent.com/16944225/34970299-af2eb162-fa84-11e7-81f0-930a619dbf85.png)

Words count can't be changed, it's only for time to read options (`time`, `total_time`).
No other settings needed, all works correct. Maybe your post is very short and u can see only minimal reading time (0:01), try to check with big post this settings.

> Btw, is the basis of reading time hour?

Basics setup as default (5, 200) — it's avarage reading time at most languges.
