### ISSUE TITLE
The time to read the article looks not correct

### ISSUE THREAD

**Issue by Allen4Tech** [theme-next/hexo-symbols-count-time#6]
The time to read the article looks not correct, please see my screenshot.

<img width="211" alt="wx20180126-092745 2x" src="https://user-images.githubusercontent.com/13222554/35420984-706b78b2-027b-11e8-8b3e-07918fc796be.png">

My config in Hexo's _config.yml file
```
symbols_count_time:
  symbols: true
  time: true
  total_symbols: true
  total_time: true
```

My config in Next theme's _config.yml file
```
symbols_count_time:
  separated_meta: true
  item_text_post: true
  item_text_total: false
  awl: 5
  wpm: 200
```
