### ISSUE TITLE
does not show anything

### ISSUE THREAD

**Issue by ehlxr** [theme-next/hexo-symbols-count-time#7]
i have followed the instructions to configure my blog, but still do not show results.

here is my operation process：

executed the order `npm install hexo-symbols-count-time --save` 

then config the content in the `_config.yml` under theme
```
# Post wordcount display settings
# Dependencies: https://github.com/theme-next/hexo-symbols-count-time
symbols_count_time:
  separated_meta: true
  item_text_post: true
  item_text_total: false
  awl: 5
  wpm: 200
```
