### ISSUE TITLE
The total number of words on the site is less than the total number of words in the article

### ISSUE THREAD

**Issue by Lammmmmmm** [theme-next/hexo-symbols-count-time#74]
Hello, I am a Chinese user. When using the following configuration, the total number of words on my website is always far less than the total number of words in all articles, as shown in the figure.

```yaml
symbols_count_time:
  separated_meta: true
  item_text_post: true
  item_text_total: true
  awl: 4
  wpm: 275
```
![image](https://user-images.githubusercontent.com/47166401/71582116-9886dd80-2b43-11ea-977b-51b2b4f27b08.png)
